### ISSUE TITLE
Crossfit

### ISSUE THREAD

**Issue by MatiasFeldman** [pdepjm/2023-tp0-presentacion-GonTurri#2]
Uf bien ahí con el crossfit, ¿cuánto es tu máximo en sentadillas y peso muerto? yo soy más de gym un poquito menos de intensidad. Ahh  y si buscas grupo para los tps y estas solo, yo también estoy solo. Muy random esto, pero tengo un amigo de ort que te conoce y también me dijo que no te dormías en los tps como me paso el año pasado con sistemas, se llama Tomas Tauscher.

**Comment by GonTurri** [comment]
Jajaja dale un gusto, tengo 120 de sentadilla y 150 de peso muerto. Son pesos humildes
